// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_practice/firebase_options.dart' show DefaultFirebaseOptions;
import '';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = DefaultFirebaseOptions(
    apiKey: 'AIzaSyCw0Cj6tByujP5xJJ5D31KwALDD-swrQDI',
    appId: '1:562338936457:web:ce1f50de0a404f3ac97858',
    messagingSenderId: '562338936457',
    projectId: 'signin-signup-firebase1',
    authDomain: 'signin-signup-firebase1.firebaseapp.com',
    storageBucket: 'signin-signup-firebase1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm6oDJ1dlxQCRZ0Evn-iRl9CJq2QZrv24',
    appId: '1:562338936457:android:ce01a2b4fc42d49fc97858',
    messagingSenderId: '562338936457',
    projectId: 'signin-signup-firebase1',
    storageBucket: 'signin-signup-firebase1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU5w9CQTXh0BAfxgoRZKRIjLX5w5l7tYE',
    appId: '1:562338936457:ios:02dd2e2a5b20fe35c97858',
    messagingSenderId: '562338936457',
    projectId: 'signin-signup-firebase1',
    storageBucket: 'signin-signup-firebase1.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );
}
